// Generated by CoffeeScript 1.5.0
(function() {
  var Backrock, View, root;

  root = this;

  if (typeof exports !== "undefined" && exports !== null) {
    Backrock = exports;
  } else {
    Backrock = root.Backrock = {};
  }

  Backrock.VERSION = '0.0.1';

  Backrock.View = View = (function() {

    function View() {}

    return View;

  })();

}).call(this);
